name: Deploy to RDP Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, windows, x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.RDP_DEPLOY_KEY }}

    - name: Deploy to RDP Host 1
      run: |
        cp web.config.rdp1 web.config
        ssh -o StrictHostKeyChecking=no ${{ secrets.RDP_USER }}@${{ secrets.RDP_HOST_1 }} powershell -Command \"cd 'E:\\APP\\Chronologix'; node -v; npm -v; git pull origin main; npm install; npm run build; Import-Module WebAdministration; Restart-WebAppPool 'chronologix'\"

    - name: Deploy to RDP Host 2
      run: |
        cp web.config.rdp2 web.config
        ssh -o StrictHostKeyChecking=no ${{ secrets.RDP_USER }}@${{ secrets.RDP_HOST_2 }} powershell -Command \"cd 'E:\\APP\\Chronologix'; node -v; npm -v; git pull origin main; npm install; npm run build; Import-Module WebAdministration; Restart-WebAppPool 'chronologix'\"
